---
name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install PNPM
        uses: pnpm/setup@v3
        with:
          install: true

      - name: Build contract
        run: pnpm run build:contract

      - name: Test contract
        run: pnpm run test:contract

      - name: Build frontend
        run: pnpm run build

      - name: Lint frontend
        run: pnpm run lint

      - name: Run frontend tests
        run: pnpm run test
        if: false

      - name: Check formatting
        run: pnpm run format:check
